### ISSUE TITLE
Multiple servers?

### ISSUE THREAD

**Issue by binaryfire** [gbrian/grafana-hetzner-datasource#2]
Hi Gustavo!

Just wondering if this will load all servers in a project, or just a single server?

Best

**Comment by gbrian** [comment]
HI @menathor ,
https://github.com/gbrian/grafana-hetzner-datasource/blob/master/load.metrics.js
Will load metrics from all servers returned by Hetznez REST API endpoint /Servers.

https://docs.hetzner.cloud/#servers-get-all-servers

**Comment by binaryfire** [comment]
@gbrian Awesome, look forward to checking this out!
